import './globals.css'

import type { Metadata } from 'next'

import { titleFont, monoFont, sansFont } from '@/fonts'

import Providers from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      suppressHydrationWarning
      className={`${sansFont.variable} ${titleFont.variable} ${monoFont.variable} overflow-hidden antialiased`}
      lang="vi"
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
