import './globals.css'

import type { Metadata } from 'next'

import { titleFont, monoFont, sansFont } from '@/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      className={`${sansFont.variable} ${titleFont.variable} ${monoFont.variable} antialiased`}
      lang="en"
    >
      <body>{children}</body>
    </html>
  )
}
