import './globals.css'

import type { Metadata } from 'next'

import { ThemeProvider } from '@/components/theme-provider'
import { titleFont, monoFont, sansFont } from '@/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      suppressHydrationWarning
      className={`${sansFont.variable} ${titleFont.variable} ${monoFont.variable} antialiased`}
      lang="vi"
    >
      <body>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
